#uzivatel zada celu vetu a program vetu rozdeli na slova, ktore vypise nahodnou farbou na nahonom mieste
#aj pismenka zo slov vypise nahodnymi farbami
#test zo stringov znakove retazce ako retazec.count, retazec.find ...