fmena = open("mena.txt","r",encoding="utf-8")
fpriezviska = open("priezviska.txt","r",encoding="utf-8")
fmena_priezviska = open("mena_priezviska.txt","w",encoding="utf-8")
for meno in fmena:
    priezvisko = fpriezviska.readline()
    print(f"{meno.strip()} {priezvisko.strip()}")
    print(f"{meno.strip()} {priezvisko.strip()}",file=fmena_priezviska)
fmena.close()
fpriezviska.close()
fmena_priezviska.close()